"""Add CRUD methods

Revision ID: 03c6544d3bad
Revises: 35110149a70d
Create Date: 2020-11-04 07:17:48.706889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c6544d3bad'
down_revision = '35110149a70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
