"""change sample to samples

Revision ID: 30419b9d14cc
Revises: 3da0b8334b80
Create Date: 2020-10-29 19:06:36.668494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30419b9d14cc'
down_revision = '3da0b8334b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
