"""add schemas

Revision ID: 35110149a70d
Revises: ed5175f94547
Create Date: 2020-11-04 01:47:31.352654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35110149a70d'
down_revision = 'ed5175f94547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
