"""change owner to user

Revision ID: 3da0b8334b80
Revises: f0ae7180d211
Create Date: 2020-10-29 19:05:15.719175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da0b8334b80'
down_revision = 'f0ae7180d211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
