"""Move snapshot from template to sample

Revision ID: 5bf8caa40835
Revises: 9711efb9fd24
Create Date: 2022-02-20 17:31:32.640956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf8caa40835'
down_revision = '9711efb9fd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('snapshot', sa.String(), nullable=True))
    op.drop_column('template', 'screenshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('screenshot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sample', 'snapshot')
    # ### end Alembic commands ###
