"""Coverage model parsed into arrays

Revision ID: 74f4ed70fc8b
Revises: fb5ed9532ab5
Create Date: 2022-03-25 19:42:31.856771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74f4ed70fc8b'
down_revision = 'fb5ed9532ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage', sa.Column('labels', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('coverage', sa.Column('values', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('coverage', 'contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage', sa.Column('contents', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('coverage', 'values')
    op.drop_column('coverage', 'labels')
    # ### end Alembic commands ###
