"""Move sequencing stats into corresponding models

Revision ID: 9711efb9fd24
Revises: e99c80ac3598
Create Date: 2022-02-18 22:54:18.688424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9711efb9fd24'
down_revision = 'e99c80ac3598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'stats')
    op.add_column('sample', sa.Column('n_reads', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('n_r1_reads_aligned', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('n_r2_reads_aligned', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('average_coverage', sa.Float(), nullable=True))
    op.add_column('sample', sa.Column('percent_complete', sa.Float(), nullable=True))
    op.add_column('sample', sa.Column('median_insert_length', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('snps', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('insertions', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('deletions', sa.Integer(), nullable=True))
    op.add_column('template', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'length')
    op.drop_column('sample', 'deletions')
    op.drop_column('sample', 'insertions')
    op.drop_column('sample', 'snps')
    op.drop_column('sample', 'median_insert_length')
    op.drop_column('sample', 'percent_complete')
    op.drop_column('sample', 'average_coverage')
    op.drop_column('sample', 'n_r2_reads_aligned')
    op.drop_column('sample', 'n_r1_reads_aligned')
    op.drop_column('sample', 'n_reads')
    op.add_column('run', sa.Column('stats', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
