"""add screenshots for real

Revision ID: e99c80ac3598
Revises: 43b321c9c05f
Create Date: 2021-03-02 00:46:10.487193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c80ac3598'
down_revision = '43b321c9c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('screenshot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'screenshot')
    # ### end Alembic commands ###
