"""change template to templates

Revision ID: ed5175f94547
Revises: 30419b9d14cc
Create Date: 2020-10-29 19:07:19.843361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5175f94547'
down_revision = '30419b9d14cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
