"""Add consensus and coverage tables

Revision ID: fb5ed9532ab5
Revises: 5bf8caa40835
Create Date: 2022-03-19 18:38:59.305281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5ed9532ab5'
down_revision = '5bf8caa40835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.String(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_id'), 'consensus', ['id'], unique=False)
    op.create_table('coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.String(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_id'), 'coverage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_id'), table_name='coverage')
    op.drop_table('coverage')
    op.drop_index(op.f('ix_consensus_id'), table_name='consensus')
    op.drop_table('consensus')
    # ### end Alembic commands ###
